INSERT INTO Filmer (film) VALUES ('Replay 1988');
INSERT INTO Filmer (film) VALUES ('My Life');
INSERT INTO Filmer (film) VALUES ('Welcome Home');
INSERT INTO Filmer (film) VALUES ('Sweet Home');
INSERT INTO Filmer (film) VALUES ('Titanic');
INSERT INTO Filmer (film) VALUES ('Moon Lovers');
INSERT INTO Filmer (film) VALUES ('Doctors');
INSERT INTO Filmer (film) VALUES ('Goblin');
INSERT INTO Filmer (film) VALUES ('Doctor Slump');
INSERT INTO Filmer (film) VALUES ('Deadpool');